# Generated by Django 3.1.5 on 2021-01-25 20:08

import Room.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=Room.models.generate_code, max_length=10, unique=True)),
                ('host_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('rooms', models.ManyToManyField(to='Room.room')),
            ],
        ),
    ]
