# Generated by Django 3.1.5 on 2021-01-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Chat Room', max_length=50),
        ),
    ]
