# Generated by Django 3.1.5 on 2021-01-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0004_auto_20210127_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='123', max_length=250),
        ),
    ]
