# Generated by Django 3.1.5 on 2021-02-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0008_auto_20210129_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='host_id',
            new_name='host_user_name',
        ),
    ]
